import { createStore } from "redux";

import reducer from "./reducer.js";

const state = {
  cards: [
    {
      id: 1,
      title: "Just Milk Semi-Skimmed 6 x 1L (Case of 2) 1",
      price: 1.59,
      image: "1.jpg",
      group: 1,
      countInCart: 2,
      isFavorites: false,
    },
    {
      id: 2,
      title: "Best-in 10 British Big Eggs 1",
      price: 1.59,
      image: "2.jpg",
      group: 4,
      countInCart: 1,
      isFavorites: true,
    },
    {
      id: 3,
      title: "Eggs Okskoe SO white 10pcs",
      price: 1.09,
      image: "3.jpg",
      group: 4,
      countInCart: 0,
      isFavorites: false,
    },
    {
      id: 4,
      title: "Eggs VkusVill Home C1 10pcs",
      price: 1.59,
      image: "4.jpg",
      group: 4,
      countInCart: 0,
      isFavorites: false,
    },
    {
      id: 5,
      title: "Eggs Roskar mega extra SV brown 10pcs",
      price: 1.95,
      image: "5.jpg",
      group: 4,
      countInCart: 0,
      isFavorites: false,
    },
    {
      id: 6,
      title: "Eggs Green line C1 Activita with selenium and brown iodine 10pcs",
      price: 3.04,
      image: "6.jpg",
      group: 4,
      countInCart: 0,
      isFavorites: true,
    },
    {
      id: 7,
      title: "Baguette Parisian classic 140g",
      price: 0.99,
      image: "7.jpg",
      group: 2,
      countInCart: 1,
      isFavorites: false,
    },
    {
      id: 8,
      title: "Bananas bunch 0.5-1.1kg",
      price: 2.25,
      image: "8.jpeg",
      group: 3,
      countInCart: 0,
      isFavorites: false,
    },
    {
      id: 9,
      title: "Milk Dairy Kingdom pasteurized 3.2% 900ml",
      price: 3.08,
      image: "9.jpg",
      group: 1,
      countInCart: 2,
      isFavorites: true,
    },
    {
      id: 10,
      title: "Vologda pasteurized milk 2.5% 970ml",
      price: 0.59,
      image: "10.jpg",
      group: 1,
      countInCart: 2,
      isFavorites: false,
    },
    {
      id: 11,
      title: "Clementines are Moroccan",
      price: 2.06,
      image: "11.jpg",
      group: 3,
      countInCart: 3,
      isFavorites: false,
    },
    {
      id: 12,
      title: "Eggs Three Layers C2 white 10pcs",
      price: 1.11,
      image: "12.jpg",
      group: 4,
      countInCart: 7,
      isFavorites: false,
    },
  ],
  address: { street: "", flat: "", floor: "", block: "" },
  payment: "",
  /*  cart: [
    { id: 1, count: 2 },
    { id: 2, count: 1 },
    { id: 7, count: 1 },
    { id: 9, count: 2 },
    { id: 10, count: 2 },
    { id: 11, count: 3 },
    { id: 12, count: 7 },
  ],
  */
};

export default createStore(reducer, state);
