import { createStore } from "redux";

import reducer from "./reducer.js";

const state = {
  cards: [
    {
      id: 1,
      title: "Just Milk Semi-Skimmed 6 x 1L (Case of 2) 1",
      price: 1.59,
      image: "1.png",
      group: 1,
      countInCart: 2,
      isFavorites: false,
    },
    {
      id: 2,
      title: "Best-in 10 British Big Eggs 1",
      price: 1.59,
      image: "4.png",
      group: 4,
      countInCart: 1,
      isFavorites: true,
    },
    {
      id: 3,
      title: "Best-in 10 British Big Eggs 2",
      price: 1.59,
      image: "4.png",
      group: 4,
      countInCart: 0,
      isFavorites: false,
    },
    {
      id: 4,
      title: "Best-in 10 British Big Eggs 3",
      price: 1.59,
      image: "4.png",
      group: 4,
      countInCart: 0,
      isFavorites: false,
    },
    {
      id: 5,
      title: "Best-in 10 British Big Eggs 4",
      price: 1.59,
      image: "4.png",
      group: 4,
      countInCart: 0,
      isFavorites: false,
    },
    {
      id: 6,
      title: "Best-in 10 British Big Eggs 5",
      price: 1.59,
      image: "4.png",
      group: 4,
      countInCart: 0,
      isFavorites: true,
    },
    {
      id: 7,
      title: "Best-in 10 British Big Eggs 1",
      price: 1.59,
      image: "2.png",
      group: 2,
      countInCart: 1,
      isFavorites: false,
    },
    {
      id: 8,
      title: "Best-in 10 British Big Eggs 1",
      price: 1.59,
      image: "3.png",
      group: 3,
      countInCart: 0,
      isFavorites: false,
    },
    {
      id: 9,
      title: "Just Milk Semi-Skimmed 6 x 1L (Case of 2) 2",
      price: 1.59,
      image: "1.png",
      group: 1,
      countInCart: 2,
      isFavorites: true,
    },
    {
      id: 10,
      title: "Just Milk Semi-Skimmed 6 x 1L (Case of 2) 3",
      price: 1.59,
      image: "1.png",
      group: 1,
      countInCart: 2,
      isFavorites: false,
    },
    {
      id: 11,
      title: "Best-in 10 British Big Eggs 2",
      price: 1.59,
      image: "3.png",
      group: 3,
      countInCart: 3,
      isFavorites: false,
    },
    {
      id: 12,
      title: "Best-in 10 British Big Eggs 1",
      price: 1.59,
      image: "5.png",
      group: 5,
      countInCart: 7,
      isFavorites: false,
    },
  ],
};

export default createStore(reducer, state);
